apiVersion: v1
kind: Pod
metadata:
  name: non-root-pod
spec:
  containers:
    - name: non-root-container
      image: nginx
      securityContext:
        runAsNonRoot: true
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
