apiVersion: v1
kind: Pod
metadata:
  name: limited-resources-pod
spec:
  containers:
    - name: limited-resources-container
      image: nginx
      resources:
        limits:
          cpu: "1"
          memory: "500Mi"
