name: Kyverno Policy Check

on:
  push:
    branches:
      - main

jobs:
  test-kyverno-policies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Validate YAML Indentation
      run: |
        if ! yamllint policies/; then
          echo "YAML indentation validation failed."
          exit 1
        fi

    - name: Simulate Apply Kyverno Policy
      run: |
        kubectl apply -f policies/require-resources-limits.yml --dry-run=client -o yaml
